version: "3.9"

services:
  central_node:
    image: mysql
    command: mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=all_movies
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/all_movies:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  node_2:
    image: mysql
    command: mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movies_before_1980
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/movies_before_1980:/docker-entrypoint-initdb.d

    ports:
      - "3307:3306"

  node_3:
    image: mysql
    command: mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movies_from_1980
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data/movies_from_1980:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-app
    ports:
      - "3000:3000"
    command: pnpm run dev
    volumes:
      - ./:/app

volumes:
  data1:
  data2:
